# Generated by Django 4.2.7 on 2023-11-27 13:19

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('LIFE_COACH', 'LIFE COACH'), ('HAND_POINTING', 'CÁCH XEM CHỈ TAY'), ('EDUCATION', 'GIÁO DỤC TIẾNG NHẬT'), ('TRANSLATE', 'PHIÊN DỊCH, DỊCH THUẬT NHẬT-VIỆT'), ('COURSE', 'KHÓA HỌC')], default='LIFE_COACH', max_length=15),
        ),
        migrations.AddField(
            model_name='blog',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
