# Generated by Django 4.2.7 on 2023-11-27 13:45

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('LIFE_COACH', 'LIFE COACH'), ('HAND_POINTING', 'CÁCH XEM CHỈ TAY'), ('EDUCATION', 'GIÁO DỤC TIẾNG NHẬT'), ('TRANSLATE', 'PHIÊN DỊCH, DỊCH THUẬT NHẬT-VIỆT'), ('COURSE', 'KHÓA HỌC')], default='LIFE_COACH', max_length=15, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='link'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.TextField(max_length=320, verbose_name='title'),
        ),
    ]
