# Generated by Django 4.2.7 on 2023-12-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_blog_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Bài viết nổi bật'),
        ),
    ]
