# Generated by Django 4.2.7 on 2023-12-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_blog_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkYoutube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=320, verbose_name='title')),
                ('link', models.URLField(blank=True, max_length=400, null=True, verbose_name='link')),
                ('short_description', models.CharField(max_length=200)),
                ('type_video', models.CharField(choices=[('VIEWS', 'XEM NHIỀU'), ('VIDEO', 'VIDEO')], default='XEM NHIỀU', max_length=15, verbose_name='type_video')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='blog',
            name='link',
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('LIFE_COACH', 'LIFE COACH'), ('HAND_POINTING', 'CÁCH XEM CHỈ TAY'), ('EDUCATION', 'GIÁO DỤC TIẾNG NHẬT'), ('TRANSLATE', 'PHIÊN DỊCH, DỊCH THUẬT NHẬT-VIỆT'), ('COURSE_LC', 'KHÓA HỌC LIFE COACH'), ('COURSE_HP', 'KHÓA HỌC CÁCH XEM CHỈ TAY'), ('INFO', 'GIỚI THIỆU')], default='LIFE_COACH', max_length=15, verbose_name='category'),
        ),
    ]
