# Generated by Django 4.2.7 on 2023-12-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_linkyoutube_userregister_remove_blog_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkyoutube',
            name='link',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='link'),
        ),
        migrations.AlterField(
            model_name='linkyoutube',
            name='short_description',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='linkyoutube',
            name='title',
            field=models.TextField(max_length=255, verbose_name='title'),
        ),
    ]
