# Generated by Django 4.2.7 on 2023-12-17 15:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_linkyoutube_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkyoutube',
            name='link',
            field=models.URLField(default=django.utils.timezone.now, max_length=300, verbose_name='link'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='linkyoutube',
            name='short_description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
