# Generated by Django 4.2.16 on 2024-11-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_blog_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinfo',
            name='address',
            field=models.CharField(max_length=320, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='webinfo',
            name='code',
            field=models.CharField(max_length=320, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='webinfo',
            name='email',
            field=models.CharField(max_length=320, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='webinfo',
            name='name',
            field=models.CharField(max_length=320, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='webinfo',
            name='slogan',
            field=models.CharField(max_length=320, verbose_name='slogan'),
        ),
        migrations.AlterField(
            model_name='webinfo',
            name='title',
            field=models.CharField(max_length=320, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='webinfo',
            name='website',
            field=models.CharField(max_length=320, verbose_name='website'),
        ),
        migrations.AlterField(
            model_name='webinfohotline',
            name='phone',
            field=models.CharField(max_length=320, verbose_name='phone'),
        ),
    ]
