# Generated by Django 4.2.16 on 2024-11-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_webinfo_address_alter_webinfo_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='short_description',
            field=models.TextField(blank=True, max_length=320, null=True, verbose_name='short_description'),
        ),
    ]
