# Generated by Django 4.2.16 on 2024-11-26 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_blog_short_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='page',
            name='type',
            field=models.CharField(choices=[('HOME', 'Trang chủ'), ('DU_HOC', 'Du học'), ('DU_LICH', 'Du lịch')], max_length=20),
        ),
        migrations.AlterField(
            model_name='webinfolink',
            name='type',
            field=models.CharField(choices=[('YOUTUBE', 'Youtube'), ('TIKTOK', 'Tiktok'), ('FACEBOOK', 'Facebook')], max_length=20),
        ),
        migrations.CreateModel(
            name='PageThumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to='page/', verbose_name='thumbnail')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_thumbnails', to='myapp.page')),
            ],
        ),
    ]
